version: '3.5'
services:
  ng-mcu:
    container_name: ng-mcu
    image: abdalem/angular:8.3.5
    # ports:
    #   - 4200:4200
    volumes:
      - ./:/var/www
    environment:
      VIRTUAL_HOST: "ng-mcu.local"
      MARVEL_API_KEY: "PUT_HERE_YOUR_MARVEL_API_KEY"
    expose:
      - "4200"
    command: ng serve --host 0.0.0.0 --publicHost ng-mcu.local
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  default:
    external:
      name: nginx-proxy